# Top-level build orchestration for pve-meta.
#
# debhelper compat 13 runs build steps under a fake, empty HOME, so rustup's `cargo`
# (~/.cargo/bin) and its default-toolchain lookup ($RUSTUP_HOME) both miss; the
# $(wildcard)/fallback-to-/root and explicit RUSTUP_HOME/CARGO_HOME below fix that.
export RUSTUP_HOME ?= $(firstword $(wildcard $(HOME)/.rustup /root/.rustup) /root/.rustup)
export CARGO_HOME ?= $(firstword $(wildcard $(HOME)/.cargo /root/.cargo) /root/.cargo)
CARGO ?= $(firstword $(wildcard $(CARGO_HOME)/bin/cargo $(HOME)/.cargo/bin/cargo /root/.cargo/bin/cargo) cargo)

DESTDIR ?=
PREFIX ?= /usr

UI_DIR := ui-extjs
# ui-extjs/src/*.js, one file per section, concatenated in name order (the
# two-digit prefix) into the one script pve-ext's page loader fetches. No
# bundler, no transform.
UI_SRC := $(sort $(wildcard $(UI_DIR)/src/*.js))
UI_JS := $(UI_DIR)/pve-meta-tree.js
MONACO := $(UI_DIR)/monaco/vs
# The browser build of pve-meta-core (crates/pve-meta-wasm), for wasm32; needs
# the target installed (`rustup target add wasm32-unknown-unknown`, or Debian's
# `libstd-rust-dev-wasm32`). No wasm-bindgen, no wasm-pack, no npm (docs/WASM-CORE.md).
WASM_TARGET := wasm32-unknown-unknown
WASM := target/$(WASM_TARGET)/wasm/pve_meta_wasm.wasm
# The editor fetches the core and Monaco itself, beside the script pve-ext
# fingerprints, and pveproxy's Last-Modified alone lets a browser pair a new
# script with a cached old core. So each is installed under a name that changes
# with its content: the core under its hash, Monaco's tree under its version.
# `make js` writes both names into the script. Expanded on use, after `make wasm`.
WASM_NAME = pve-meta-core-$(shell sha256sum $(WASM) | cut -c1-8).wasm
MONACO_VERSION := $(shell sed -n 's/.*"monaco-editor": *"\([^"]*\)".*/\1/p' $(UI_DIR)/package.json)
MONACO_DIR := monaco-$(MONACO_VERSION)

.PHONY: build ui js wasm deb install install-guest-files clean check check-perl test doc

build: wasm js
	$(MAKE) -C crates/pve-meta-perl BUILD_MODE=release
	$(CARGO) build --release -p pve-meta-guest-files

wasm:
	$(CARGO) build -p pve-meta-wasm --target $(WASM_TARGET) --profile wasm

js: $(UI_JS)

# Only when missing (`make js` alone): `make wasm` is what rebuilds it.
$(WASM):
	$(MAKE) wasm

$(UI_JS): $(UI_SRC) $(WASM) $(UI_DIR)/package.json
	{ echo "// Generated by make from ui-extjs/src/*.js -- edit the sources, not this file."; cat $(UI_SRC); } \
		| sed -e 's/@WASM_NAME@/$(WASM_NAME)/g' -e 's/@MONACO_DIR@/$(MONACO_DIR)/g' > $@
	@if command -v node >/dev/null 2>&1; then node --check $@; fi

# Fetches Monaco's minified AMD tree into ui-extjs/monaco/vs, to ship in the
# package (never loaded from a CDN). Tolerant of `npm` being absent: the editor
# then degrades (no Text card, no diff) instead of failing the build.
# A stale vendored tree is worse than none: the editor would ship whatever
# version happened to be there instead of package.json's pin. So refresh
# whenever the vendored copy disagrees with the pin, not just when absent, and
# without npm drop it: install names the tree after the pin (MONACO_DIR).
ui:
	@pinned=$(MONACO_VERSION); \
	have=""; \
	if [ -f $(UI_DIR)/node_modules/monaco-editor/package.json ]; then \
		have=$$(grep -m1 '"version"' $(UI_DIR)/node_modules/monaco-editor/package.json | sed 's/[^0-9.]//g'); \
	fi; \
	if [ -d $(MONACO) ] && [ -n "$$have" ] && [ "$$have" = "$$pinned" ]; then \
		echo "monaco $$have already vendored in $(MONACO)"; \
	elif command -v npm >/dev/null 2>&1; then \
		if [ -d $(MONACO) ] && [ "$$have" != "$$pinned" ]; then \
			echo "monaco vendored is $$have, pin is $$pinned: re-vendoring"; \
		fi; \
		rm -rf $(MONACO) $(UI_DIR)/node_modules; \
		(cd $(UI_DIR) && npm install --no-audit --no-fund); \
		mkdir -p $(MONACO); \
		cp -a $(UI_DIR)/node_modules/monaco-editor/min/vs/. $(MONACO)/; \
	else \
		rm -rf $(MONACO); \
		echo "warning: npm not found, packaging without Monaco (no Text card, no diff)" >&2; \
	fi

# pve-meta consumes pve-ext's three generic seams (docs/DESIGN.md §8,
# pve-ext/README.md): the API module (auto-discovered), the UI pages
# (pages/*.json), and the managed lifecycle patch. Three binary packages come
# from this source (debian/control): `pve-meta` (below), `libpve-meta-rs-perl`
# (crates/pve-meta-perl's own `install`, PACKAGING.md), and `pve-meta-guest-files`
# (install-guest-files, below).
install: js
	if [ -f perl/PVE/API2/Ext/Meta.pm ]; then \
		install -D -m 0644 perl/PVE/API2/Ext/Meta.pm $(DESTDIR)$(PREFIX)/share/perl5/PVE/API2/Ext/Meta.pm; \
	else \
		echo "warning: perl/PVE/API2/Ext/Meta.pm not present yet, skipping" >&2; \
	fi
	# The lifecycle patch manifest, under the name the maintainer scripts apply it by.
	install -D -m 0644 patches/lifecycle.json $(DESTDIR)$(PREFIX)/share/pve-ext/patches/pve-meta-lifecycle.json
	mkdir -p $(DESTDIR)$(PREFIX)/share/pve-ext/patches/lifecycle
	cp patches/lifecycle/*.diff $(DESTDIR)$(PREFIX)/share/pve-ext/patches/lifecycle/
	# In sbin, not an API client's path: it reads /etc/pve/meta directly, often
	# before pveproxy is reachable (docs/DESIGN.md §8).
	install -D -m 0755 bin/pve-meta $(DESTDIR)$(PREFIX)/sbin/pve-meta
	# Not executable in place; an administrator copies it into a storage's
	# snippets directory, where PVE looks for hookscripts.
	install -D -m 0644 examples/maintenance-hook.pl \
		$(DESTDIR)$(PREFIX)/share/doc/pve-meta/examples/maintenance-hook.pl
	# Documentation only: pve-meta ships no live prefix of its own. The packaged
	# prefix directory (docs/DESIGN.md §3) is created empty for an operator's
	# own .deb to drop into.
	install -D -m 0644 examples/prefixes/traefik.yaml \
		$(DESTDIR)$(PREFIX)/share/doc/pve-meta/examples/prefixes/traefik.yaml
	mkdir -p $(DESTDIR)$(PREFIX)/share/pve-meta/prefixes
	# Two pve-ext UI-page manifests (a guest tab, a datacenter tab) naming
	# different `xtype`s out of the one script the loader fetches.
	install -D -m 0644 pages/pve-meta.json $(DESTDIR)$(PREFIX)/share/pve-ext/pages/pve-meta.json
	install -D -m 0644 pages/pve-meta-dc.json $(DESTDIR)$(PREFIX)/share/pve-ext/pages/pve-meta-dc.json
	install -D -m 0644 $(UI_JS) $(DESTDIR)$(PREFIX)/share/pve-manager/js/pve-meta-extjs/pve-meta-tree.js
	# Not optional: without it the editor cannot read a document.
	install -D -m 0644 $(WASM) $(DESTDIR)$(PREFIX)/share/pve-manager/js/pve-meta-extjs/$(WASM_NAME)
	# Absent when the build host had no npm; the panel then degrades.
	if [ -d $(MONACO) ]; then \
		mkdir -p $(DESTDIR)$(PREFIX)/share/pve-manager/js/pve-meta-extjs/$(MONACO_DIR)/vs; \
		cp -a $(MONACO)/. $(DESTDIR)$(PREFIX)/share/pve-manager/js/pve-meta-extjs/$(MONACO_DIR)/vs/; \
	fi

# The pve-meta-guest-files package (docs/GUEST-FILES.md): the daemon, in sbin since it
# writes into containers as root, and the `guest-files` prefix it reads. The
# systemd unit (debian/pve-meta-guest-files.service) is installed by dh_installsystemd.
install-guest-files:
	install -D -m 0755 target/release/pve-meta-guest-files $(DESTDIR)$(PREFIX)/sbin/pve-meta-guest-files
	install -D -m 0644 crates/pve-meta-guest-files/prefixes/guest-files.yaml \
		$(DESTDIR)$(PREFIX)/share/pve-meta/prefixes/guest-files.yaml

# Builds every package this repo ships: pve-ext's own source package (moving its
# artifacts up from pve-ext/'s parent to sit next to this package's own), then
# this source package's three binaries (debian/control). lintian's default (an
# E: tag fails, a W: doesn't) is fatal only when $CI is set, so a local build
# isn't blocked by an unrelated nag.
deb:
	$(MAKE) -C pve-ext deb
	for f in pve-ext_*.deb pve-ext_*.buildinfo pve-ext_*.changes; do [ -e "$$f" ] && mv -f "$$f" ..; done
	dpkg-buildpackage -b -us -uc -d
	if [ -n "$$CI" ]; then \
		lintian ../pve-meta_*.deb ../libpve-meta-rs-perl_*.deb ../pve-meta-guest-files_*.deb ../pve-ext_*.deb; \
	else \
		lintian ../pve-meta_*.deb ../libpve-meta-rs-perl_*.deb ../pve-meta-guest-files_*.deb ../pve-ext_*.deb || true; \
	fi

# A broken intra-doc link is caught here but not by clippy; needs no libperl,
# so it also runs on a workstation.
doc:
	RUSTDOCFLAGS="-D warnings" $(CARGO) doc --no-deps -p pve-meta-core -p pve-meta-guest-files

check: doc wasm js
	$(CARGO) clippy --workspace -- -D warnings
	# Drives the editor's helpers through the shipped `.wasm`: codec, row
	# builder, staging model and schema findings.
	@if command -v node >/dev/null 2>&1; then \
		node ui-extjs/testing/smoke.js; \
	else \
		echo "warning: node not found, skipping the ui-extjs smoke suite" >&2; \
	fi

# Every shell and Perl file, compiled but not run, against stubbed PVE modules
# (scripts/perl-stubs) so this runs on a laptop and in CI's plain Debian
# container too.
check-perl:
	shellcheck pve-ext/bin/pve-ext-patch
	@for f in perl/PVE/API2/Ext/Meta.pm pve-ext/perl/PVE/API2/Ext.pm \
	          bin/pve-meta examples/maintenance-hook.pl; do \
		perl -Iscripts/perl-stubs -c $$f || exit 1; \
	done

test:
	$(CARGO) test -p pve-meta-core -p pve-meta-wasm -p pve-meta-guest-files

clean:
	$(CARGO) clean
	rm -f $(UI_JS)
