[package]
name = "pve-metad"
description = "pve-meta: HTTPS API daemon"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "pve-metad"
path = "src/main.rs"

[dependencies]
pve-meta-api = { path = "../pve-meta-api" }
pve-meta-core = { path = "../pve-meta-core" }

anyhow.workspace = true
tracing.workspace = true

tokio.workspace = true
futures.workspace = true
http.workspace = true
hyper.workspace = true
hyper-util.workspace = true
openssl.workspace = true

proxmox-router.workspace = true
proxmox-rest-server.workspace = true
proxmox-daemon.workspace = true
proxmox-log.workspace = true
proxmox-http.workspace = true
proxmox-systemd.workspace = true
