//! `pve-meta-rs`: the `PVE::RS::Meta` Perl bindings.
//!
//! Three families of exports, all thin wrappers over [`pve_meta_core`]:
//!
//! * the **snapshot hooks** (`on_snapshot`/`on_rollback`/`on_delsnap`), called
//!   from the one patched PVE Perl file (`PVE/AbstractConfig.pm`, package
//!   `libpve-guest-common-perl`; `docs/DESIGN.md` §6). These are the only
//!   lifecycle hooks that exist: destroy is a GC, clone and backup are not
//!   carried;
//! * **`gc`**, run by a systemd timer on every node under the cluster lock,
//!   which removes documents and snapshot copies whose vmid has left the
//!   vmlist; and
//! * the **`api_*` functions** backing `perl/PVE/API2/Ext/Meta.pm`
//!   (`docs/DESIGN.md` §5), implemented in [`pve_meta_core::api`] — this
//!   crate only supplies the store and the registry.
//!
//! **Everything crosses as a native Perl structure** (`docs/DESIGN.md` §5):
//! the caller's ACL hash and tags in, guest rows in, documents and results
//! out. The single exception is the client-supplied `data` parameter, which
//! is a JSON string because that is what the REST parameter is; it is decoded
//! once, in Rust. `perlmod` converts a Perl scalar to a `bool` by truthiness,
//! so the ACL flags are ordinary `1`/`0` (or `undef`) on the Perl side —
//! `test/basic.pl` asserts that.
//!
//! Built as a `cdylib` (`libpve_meta_rs.so`); the `.pm` glue files
//! (`PVE/RS/Meta.pm`, `Proxmox/Lib/PVEMeta.pm`) are generated separately by
//! `genpackage.pl` (see `Makefile`), not by this crate.
//!
//! The store root defaults to `/etc/pve/meta` and can be overridden with the
//! `PVE_META_ROOT` environment variable (used by tests and by
//! `test/basic.pl`); the registration directories likewise with
//! `PVE_META_OPERATOR_DIRS`.

use std::path::PathBuf;

use pve_meta_core::store::{MetaStore, RollbackOutcome};

/// Opens a fresh [`MetaStore`] rooted at `$PVE_META_ROOT`, or
/// `/etc/pve/meta` if unset. Cheap: `MetaStore::new` does no I/O.
fn open_store() -> MetaStore {
    let root = std::env::var_os("PVE_META_ROOT")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("/etc/pve/meta"));
    MetaStore::new(root)
}

/// The `Proxmox::Lib::PVEMeta` library-loader package generated by
/// `genpackage.pl` (`--lib-package=Proxmox::Lib::PVEMeta`, see `Makefile`)
/// bootstraps itself on `use` (its own generated `BEGIN` block), so this crate
/// must export a matching `boot_Proxmox__Lib__PVEMeta` symbol even though it
/// has no functions of its own to export -- mirrors upstream `pve-rs`'s
/// `Proxmox::Lib::PVE` package (`proxmox-perl-rs/pve-rs/src/bindings/mod.rs`).
#[perlmod::package(name = "Proxmox::Lib::PVEMeta", lib = "pve_meta_rs")]
mod proxmox_lib_pve_meta {}

#[perlmod::package(name = "PVE::RS::Meta", lib = "pve_meta_rs")]
mod pve_rs_meta {
    //! The `PVE::RS::Meta` package: the guest snapshot hooks, the store GC,
    //! and the `api_*` functions used by `PVE::API2::Ext::Meta`.

    use anyhow::Error;

    use pve_meta_core::api::{self, CallerAcl, GuestInput};
    use pve_meta_core::registry::{self, Registration};

    use super::{open_store, RollbackOutcome};

    /// Every operator registration, packaged then cluster-wide, with a
    /// cluster file overriding the packaged one of the same name
    /// (`docs/DESIGN.md` §3). Read per request: the directories are tiny and
    /// pmxcfs caches them, and a stale registry would be a stale grant.
    fn open_registry() -> Vec<Registration> {
        registry::load_default()
    }

    // -- snapshot hooks (`docs/DESIGN.md` §6) -----------------------------
    //
    // Called from the patched `PVE/AbstractConfig.pm`. They run inside PVE's
    // own guest locks and copy whole files; they do not consult grants.

    /// Copies `$vmid`'s current document to its `$snapname` snapshot file.
    /// A no-op if the guest has no document.
    ///
    /// Returns `1` if a copy was made, `0` otherwise.
    #[export]
    pub fn on_snapshot(vmid: u32, snapname: &str) -> Result<bool, Error> {
        Ok(open_store().snapshot(vmid, snapname)?)
    }

    /// Restores `$vmid`'s `$snapname` snapshot copy over its current
    /// document. If no snapshot copy exists but a current document does, the
    /// current document is removed (the guest had no metadata when the
    /// snapshot was taken).
    ///
    /// Returns `"restored"`, `"removed"`, or `"none"`.
    #[export]
    pub fn on_rollback(vmid: u32, snapname: &str) -> Result<String, Error> {
        let outcome = open_store().rollback(vmid, snapname)?;
        Ok(match outcome {
            RollbackOutcome::Restored => "restored",
            RollbackOutcome::RemovedNoSnapshot => "removed",
            RollbackOutcome::NoOp => "none",
        }
        .to_string())
    }

    /// Removes `$vmid`'s `$snapname` snapshot copy. Idempotent.
    ///
    /// Returns `1` if a copy existed and was removed, `0` otherwise.
    #[export]
    pub fn on_delsnap(vmid: u32, snapname: &str) -> Result<bool, Error> {
        let store = open_store();
        let existed = store.list_snapshots(vmid)?.iter().any(|n| n == snapname);
        store.delete_snapshot(vmid, snapname)?;
        Ok(existed)
    }

    // -- garbage collection (`docs/DESIGN.md` §6) --------------------------

    /// Removes every document **and snapshot copy** whose vmid is not in
    /// `$vmids` — the vmlist the caller passes in as a native array ref.
    /// Returns the number of files removed.
    ///
    /// This is what replaces the `on_destroy` hook and, with it, the whole
    /// orphan concept: there is no orphan listing, no orphan grant rule and
    /// no orphan delete in the API. A systemd timer runs it on every node;
    /// the caller must hold the cluster lock, since `/etc/pve/meta` is one
    /// pmxcfs directory shared by every node.
    ///
    /// The datacenter document is never a guest and is never removed.
    #[export]
    pub fn gc(vmids: Vec<u32>) -> Result<usize, Error> {
        api::gc(&open_store(), &vmids)
    }

    /// Returns this crate's version string. Used by
    /// `crates/pve-meta-perl/test/basic.pl` and available to operators for
    /// checking which build a running pvedaemon/pveproxy has loaded.
    #[export]
    pub fn version() -> String {
        env!("CARGO_PKG_VERSION").to_string()
    }

    // -- API-shaped exports (`PVE::API2::Ext::Meta`, `docs/DESIGN.md` §5) --
    //
    // Thin wrappers over `pve_meta_core::api` (see that module's docs for the
    // wire contract and the authorization rules). All of these die with a
    // Rust `anyhow::Error` whose `Display` is `"NNN: message"` (an HTTP
    // status prefix); the Perl layer parses that prefix and re-raises via
    // `PVE::Exception::raise`.
    //
    // `$acl` is a native hash: `{ authid, read, write, tags => [...] }`,
    // where `read`/`write` are the PVE ACL answers for the document being
    // addressed and `tags` are the guest's PVE tags, which resolve the
    // registrations' selectors. Rust computes the caller's scopes from it.

    /// `GET /meta/version` -> `{ token, changed }`.
    #[export]
    pub fn api_version() -> Result<api::ApiVersion, Error> {
        api::version(&open_store())
    }

    /// `GET /meta/operators` -> every registration, as native hashes.
    #[export]
    pub fn api_operators() -> Result<Vec<Registration>, Error> {
        Ok(api::operators(&open_registry()))
    }

    /// `GET /meta/access` -> `{ read, write, scopes }` for one document,
    /// with the registrations' selectors already resolved against `$acl`'s
    /// tags. `$id` is a vmid or `"datacenter"`.
    #[export]
    pub fn api_access(id: &str, acl: CallerAcl) -> Result<api::ApiAccess, Error> {
        let doc_id = api::parse_id(id)?;
        Ok(api::access(&open_registry(), doc_id, &acl))
    }

    /// `GET /meta/guests`. `$guests` is the array of vmlist rows Perl already
    /// has — `[{vmid, node, type, name, tags, read, write}]` — as a native
    /// array of hashes. Rust never reads `.vmlist` or a guest config itself.
    #[export]
    pub fn api_list_guests(
        authid: &str,
        guests: Vec<GuestInput>,
        has: Option<&str>,
    ) -> Result<Vec<api::GuestListEntry>, Error> {
        api::list_guests(&open_store(), &open_registry(), authid, &guests, has)
    }

    /// `GET /meta/guests/{vmid}` / `GET /meta/datacenter` (`$id` is a vmid
    /// or `"datacenter"`).
    #[export]
    pub fn api_get(
        id: &str,
        view: Option<&str>,
        format: &str,
        acl: CallerAcl,
    ) -> Result<api::ApiViewDocument, Error> {
        api::get_document(&open_store(), &open_registry(), id, view, format, &acl)
    }

    /// `PUT /meta/guests/{vmid}` / `PUT /meta/datacenter`.
    ///
    /// `$payload` is the only string crossing: the client's `data` (JSON) or
    /// `text` (YAML) parameter, decoded once in Rust.
    ///
    /// The caller (`PVE::API2::Ext::Meta`) must already hold the document's
    /// `cfs_lock_domain` lock: the digest precondition is re-checked inside
    /// this call, but only a lock makes the read-modify-write atomic across
    /// nodes (`docs/DESIGN.md` §4).
    #[export]
    #[allow(clippy::too_many_arguments)] // matches the PUT endpoint's parameter set 1:1 (docs/DESIGN.md §5)
    pub fn api_put(
        id: &str,
        view: Option<&str>,
        format: &str,
        payload: &str,
        mode: &str,
        digest: Option<&str>,
        dry_run: bool,
        acl: CallerAcl,
    ) -> Result<api::ApiPutResult, Error> {
        api::put_document(
            &open_store(),
            &open_registry(),
            id,
            view,
            format,
            payload,
            mode,
            digest,
            dry_run,
            &acl,
        )
    }

    /// `DELETE /meta/guests/{vmid}` / `DELETE /meta/datacenter`. Removes the
    /// current document only -- never a snapshot copy.
    #[export]
    pub fn api_delete(
        id: &str,
        view: Option<&str>,
        digest: Option<&str>,
        acl: CallerAcl,
    ) -> Result<api::ApiPutResult, Error> {
        api::delete_document(&open_store(), &open_registry(), id, view, digest, &acl)
    }
}
