//! `pve-meta-rs`: the `PVE::RS::Meta` Perl bindings.
//!
//! Three families of exports, all thin wrappers over [`pve_meta_core`]:
//!
//! * the **snapshot hooks** (`on_snapshot`/`on_rollback`/`on_delsnap`), called
//!   from the one patched PVE Perl file (`PVE/AbstractConfig.pm`, package
//!   `libpve-guest-common-perl`; `docs/DESIGN.md` §6). These are the only
//!   lifecycle hooks that exist: destroy is a GC, clone and backup are not
//!   carried;
//! * the **GC** (`gc_candidates`/`gc_purge`, and the unvalidated whole-sweep
//!   `gc`), run by hand from `/usr/libexec/pve-meta/gc` under the cluster lock
//!   -- nothing runs it on a timer (`docs/DESIGN.md` §6),
//!   which removes documents and snapshot copies whose vmid has left the
//!   vmlist; and
//! * the **`api_*` functions** backing `perl/PVE/API2/Ext/Meta.pm`
//!   (`docs/DESIGN.md` §5), implemented in [`pve_meta_core::api`] — this
//!   crate only supplies the store and the registry.
//!
//! **Everything crosses as a native Perl structure** (`docs/DESIGN.md` §5):
//! the caller's ACL hash and tags in, guest rows in, documents and results
//! out. The single exception is the client-supplied `data` parameter, which
//! is a JSON string because that is what the REST parameter is; it is decoded
//! once, in Rust. `perlmod` converts a Perl scalar to a `bool` by truthiness,
//! so the ACL flags are ordinary `1`/`0` (or `undef`) on the Perl side —
//! `test/basic.pl` asserts that.
//!
//! Built as a `cdylib` (`libpve_meta_rs.so`); the `.pm` glue files
//! (`PVE/RS/Meta.pm`, `Proxmox/Lib/PVEMeta.pm`) are generated separately by
//! `genpackage.pl` (see `Makefile`), not by this crate.
//!
//! The store root defaults to `/etc/pve/meta` and can be overridden with the
//! `PVE_META_ROOT` environment variable (used by tests and by
//! `test/basic.pl`); the registration directories likewise with
//! `PVE_META_NAMESPACE_DIRS`/`PVE_META_GRANT_DIRS`.

use std::path::PathBuf;

use pve_meta_core::store::{MetaStore, RollbackOutcome};

/// Opens a fresh [`MetaStore`] rooted at `$PVE_META_ROOT`, or
/// `/etc/pve/meta` if unset. Cheap: `MetaStore::new` does no I/O.
fn open_store() -> MetaStore {
    let root = std::env::var_os("PVE_META_ROOT")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("/etc/pve/meta"));
    MetaStore::new(root)
}

/// The `Proxmox::Lib::PVEMeta` library-loader package generated by
/// `genpackage.pl` (`--lib-package=Proxmox::Lib::PVEMeta`, see `Makefile`)
/// bootstraps itself on `use` (its own generated `BEGIN` block), so this crate
/// must export a matching `boot_Proxmox__Lib__PVEMeta` symbol even though it
/// has no functions of its own to export -- mirrors upstream `pve-rs`'s
/// `Proxmox::Lib::PVE` package (`proxmox-perl-rs/pve-rs/src/bindings/mod.rs`).
#[perlmod::package(name = "Proxmox::Lib::PVEMeta", lib = "pve_meta_rs")]
mod proxmox_lib_pve_meta {}

#[perlmod::package(name = "PVE::RS::Meta", lib = "pve_meta_rs")]
mod pve_rs_meta {
    //! The `PVE::RS::Meta` package: the guest snapshot hooks, the store GC,
    //! and the `api_*` functions used by `PVE::API2::Ext::Meta`.

    use anyhow::Error;

    use pve_meta_core::api::{self, CallerAcl, GuestInput};
    use pve_meta_core::registry::{self, Grant, Namespace};

    use super::{open_store, RollbackOutcome};

    /// Every grant (`docs/DESIGN.md` §3.2). Cluster-only on purpose: an
    /// operator's `.deb` may ship a namespace but must never ship its own
    /// grant. Read per request — the directory is tiny, pmxcfs caches it, and
    /// a stale grant is a wrong answer about who may write.
    fn open_grants() -> Vec<Grant> {
        registry::load_grants_default()
    }

    /// Every namespace, packaged then cluster-wide, most-specific prefix first
    /// (`docs/DESIGN.md` §3.1). Read per request, like the grants: the
    /// directories are tiny, pmxcfs caches them, and a stale namespace would be
    /// a stale schema.
    fn open_namespaces() -> Vec<Namespace> {
        registry::load_namespaces_default()
    }

    // -- snapshot hooks (`docs/DESIGN.md` §6) -----------------------------
    //
    // Called from the patched `PVE/AbstractConfig.pm`. They run inside PVE's
    // own guest locks and copy whole files; they do not consult grants.

    /// Copies `$vmid`'s current document to its `$snapname` snapshot file.
    /// A no-op if the guest has no document.
    ///
    /// Returns `1` if a copy was made, `0` otherwise.
    #[export]
    pub fn on_snapshot(vmid: u32, snapname: &str) -> Result<bool, Error> {
        Ok(open_store().snapshot(vmid, snapname)?)
    }

    /// Restores `$vmid`'s `$snapname` snapshot copy over its current
    /// document. If no snapshot copy exists but a current document does, the
    /// current document is removed (the guest had no metadata when the
    /// snapshot was taken).
    ///
    /// Returns `"restored"`, `"removed"`, or `"none"`.
    #[export]
    pub fn on_rollback(vmid: u32, snapname: &str) -> Result<String, Error> {
        let outcome = open_store().rollback(vmid, snapname)?;
        Ok(match outcome {
            RollbackOutcome::Restored => "restored",
            RollbackOutcome::RemovedNoSnapshot => "removed",
            RollbackOutcome::NoOp => "none",
        }
        .to_string())
    }

    /// Removes `$vmid`'s `$snapname` snapshot copy. Idempotent.
    ///
    /// Returns `1` if a copy existed and was removed, `0` otherwise.
    #[export]
    pub fn on_delsnap(vmid: u32, snapname: &str) -> Result<bool, Error> {
        Ok(open_store().delete_snapshot(vmid, snapname)?)
    }

    // -- garbage collection (`docs/DESIGN.md` §6) --------------------------

    /// Clears any metadata left at `$vmid` — the document and every snapshot copy.
    /// Returns the number of files removed.
    ///
    /// Called from the patched `PVE::AbstractConfig::create_and_lock_config` **only when
    /// that call asserted the vmid was unused** (`$allow_existing` false, i.e.
    /// `PVE::Cluster::check_vmid_unused` has just passed). A genuinely new guest starts
    /// with no inherited metadata; a restore *over* an existing guest keeps its document,
    /// since a backup does not carry one and clearing would be data loss.
    ///
    /// This is what closes the vmid-reuse window a periodic sweep cannot: a guest
    /// destroyed and recreated at the same vmid between two sweeps is never stale from
    /// the sweep's point of view, because the vmid is back in the vmlist.
    #[export]
    pub fn on_create(vmid: u32) -> Result<usize, Error> {
        Ok(open_store().purge(vmid)?)
    }

    /// Removes `$vmid`'s document and every snapshot copy. Returns the number of files
    /// removed; idempotent, and 0 when there was nothing there.
    ///
    /// Called from the patched `PVE::AbstractConfig::destroy_config`, after the guest
    /// config itself has been unlinked — so it runs on every destroy path there is
    /// (primary destroy, create/restore failure cleanup, clone failure cleanup, remote
    /// migration abort), all of which funnel through that one method.
    #[export]
    pub fn on_destroy(vmid: u32) -> Result<usize, Error> {
        Ok(open_store().purge(vmid)?)
    }

    /// The stale vmids: everything the store holds a file for that is not in
    /// `$vmids`, the vmlist the caller passes in as a native array ref.
    /// Removes nothing.
    ///
    /// The first half of the two-phase GC `/usr/libexec/pve-meta/gc` runs:
    /// this under `cfs_lock_domain('pve-meta-gc')`, then one
    /// [`gc_purge`](Self::gc_purge) per vmid under that vmid's own
    /// `cfs_lock_domain("pve-meta-$vmid")`. Splitting it is what closes the
    /// window in which a `PUT` that landed after the vmlist was read had its
    /// fresh document purged.
    #[export]
    pub fn gc_candidates(vmids: Vec<u32>) -> Result<Vec<u32>, Error> {
        api::gc_candidates(&open_store(), &vmids)
    }

    /// Removes `$vmid`'s document **and every snapshot copy**, but only if
    /// `$live` — a vmlist the caller re-read *inside*
    /// `cfs_lock_domain("pve-meta-$vmid")` — still does not contain it.
    /// Returns the number of files removed, `0` if the guest is live again.
    ///
    /// Dies if `$live` is empty: an empty vmlist means "every guest is gone",
    /// which is also what a process that has not called
    /// `PVE::Cluster::cfs_update()` sees.
    #[export]
    pub fn gc_purge(vmid: u32, live: Vec<u32>) -> Result<usize, Error> {
        api::gc_purge(&open_store(), vmid, &live)
    }

    /// The unvalidated whole sweep: removes every document **and snapshot
    /// copy** whose vmid is not in `$vmids`, in one pass, holding no
    /// per-vmid lock. Returns the number of files removed.
    ///
    /// This is what replaces the `on_destroy` hook and, with it, the whole
    /// orphan concept: there is no orphan listing, no orphan grant rule and
    /// no orphan delete in the API. The datacenter document is never a guest
    /// and is never removed.
    ///
    /// **Not what the timer runs.** It cannot re-validate a candidate against
    /// a vmlist read under that document's write lock, so a `PUT` that landed
    /// after `$vmids` was read loses its document silently; new callers want
    /// `gc_candidates` + `gc_purge`.
    ///
    /// Dies on an empty `$vmids`, like `gc_purge`: it is indistinguishable
    /// from a caller that has not run `PVE::Cluster::cfs_update()`.
    #[export]
    pub fn gc(vmids: Vec<u32>) -> Result<usize, Error> {
        api::gc(&open_store(), &vmids)
    }

    /// Returns this crate's version string. Used by
    /// `crates/pve-meta-perl/test/basic.pl` and available to operators for
    /// checking which build a running pvedaemon/pveproxy has loaded.
    #[export]
    pub fn version() -> String {
        env!("CARGO_PKG_VERSION").to_string()
    }

    // -- API-shaped exports (`PVE::API2::Ext::Meta`, `docs/DESIGN.md` §5) --
    //
    // Thin wrappers over `pve_meta_core::api` (see that module's docs for the
    // wire contract and the authorization rules). All of these die with a
    // Rust `anyhow::Error` whose `Display` is `"NNN: message"` (an HTTP
    // status prefix); the Perl layer parses that prefix and re-raises via
    // `PVE::Exception::raise`.
    //
    // `$acl` is a native hash: `{ authid, read, write, tags => [...] }`,
    // where `read`/`write` are the PVE ACL answers for the document being
    // addressed and `tags` are the guest's PVE tags, which resolve the
    // registrations' selectors. Rust computes the caller's scopes from it.

    /// `GET /meta/version` -> `{ token, changed }`, plus `documents`
    /// (`[{ id, digest }]`, sorted) when `$detail` is true.
    #[export]
    pub fn api_version(detail: bool) -> Result<api::ApiVersion, Error> {
        api::version(&open_store(), detail)
    }

    /// `GET /meta/grants` -> every grant, as native hashes.
    #[export]
    pub fn api_grants() -> Result<Vec<Grant>, Error> {
        Ok(api::grants_list(&open_grants()))
    }

    /// `GET /meta/namespaces` -> every namespace, most-specific first.
    #[export]
    pub fn api_namespaces() -> Result<Vec<Namespace>, Error> {
        Ok(api::namespaces_list(&open_namespaces()))
    }

    /// `GET /meta/schemas` -> `{ namespace, grant }`, the two registry file
    /// formats described in the same dialect a namespace uses, so the editor
    /// can show one as a typed tree.
    #[export]
    pub fn api_schemas() -> Result<pve_meta_core::model::Value, Error> {
        Ok(api::schemas())
    }

    /// `GET /meta/access` -> `{ read, write, scopes }` for one document,
    /// with the registrations' selectors already resolved against `$acl`'s
    /// tags. `$id` is a vmid or `"datacenter"`.
    #[export]
    pub fn api_access(id: &str, acl: CallerAcl) -> Result<api::ApiAccess, Error> {
        let doc_id = api::parse_id(id)?;
        Ok(api::access(&open_grants(), &doc_id, &acl))
    }

    /// `GET /meta/guests`. `$guests` is the array of vmlist rows Perl already
    /// has — `[{vmid, node, type, name, tags, read, write}]` — as a native
    /// array of hashes. Rust never reads `.vmlist` or a guest config itself.
    #[export]
    pub fn api_list_guests(
        authid: &str,
        guests: Vec<GuestInput>,
        has: Option<&str>,
    ) -> Result<Vec<api::GuestListEntry>, Error> {
        api::list_guests(&open_store(), &open_grants(), authid, &guests, has)
    }

    /// `GET /meta/guests/{vmid}` / `GET /meta/datacenter` (`$id` is a vmid
    /// or `"datacenter"`).
    #[export]
    pub fn api_get(
        id: &str,
        view: Option<&str>,
        format: &str,
        acl: CallerAcl,
    ) -> Result<api::ApiViewDocument, Error> {
        api::get_document(&open_store(), &open_grants(), id, view, format, &acl)
    }

    /// `PUT /meta/guests/{vmid}` / `PUT /meta/datacenter`.
    ///
    /// `$payload` is the only string crossing: the client's `data` (JSON) or
    /// `text` (YAML) parameter, decoded once in Rust.
    ///
    /// The caller (`PVE::API2::Ext::Meta`) must already hold the document's
    /// `cfs_lock_domain` lock: the digest precondition is re-checked inside
    /// this call, but only a lock makes the read-modify-write atomic across
    /// nodes (`docs/DESIGN.md` §4).
    #[export]
    #[allow(clippy::too_many_arguments)] // matches the PUT endpoint's parameter set 1:1 (docs/DESIGN.md §5)
    pub fn api_put(
        id: &str,
        view: Option<&str>,
        format: &str,
        payload: &str,
        mode: &str,
        digest: Option<&str>,
        dry_run: bool,
        acl: CallerAcl,
    ) -> Result<api::ApiPutResult, Error> {
        api::put_document(
            &open_store(),
            &open_grants(),
            id,
            view,
            format,
            payload,
            mode,
            digest,
            dry_run,
            &acl,
        )
    }

    /// `DELETE /meta/guests/{vmid}` / `DELETE /meta/datacenter`. Removes the
    /// current document only -- never a snapshot copy.
    #[export]
    pub fn api_delete(
        id: &str,
        view: Option<&str>,
        digest: Option<&str>,
        acl: CallerAcl,
    ) -> Result<api::ApiPutResult, Error> {
        api::delete_document(&open_store(), &open_grants(), id, view, digest, &acl)
    }
}
