//! `pve-meta-rs`: the `PVE::RS::Meta` Perl bindings.
//!
//! Two families of exports, both thin wrappers over [`pve_meta_core`]:
//!
//! * the **guest lifecycle hooks** (`on_snapshot`/`on_rollback`/`on_delsnap`/
//!   `on_clone`/`on_destroy`, `export_for_backup`/`import_from_backup`,
//!   `list_snapshots`/`has_document`), called from the patched PVE Perl code
//!   (`patches/lifecycle/`, `docs/LIFECYCLE-PATCHES.md`), and
//! * the **`api_*` functions** backing `perl/PVE/API2/Ext/Meta.pm`
//!   (`docs/DESIGN.md` §3), which are implemented in
//!   [`pve_meta_core::api`] — this crate only supplies the store.
//!
//! Built as a `cdylib` (`libpve_meta_rs.so`); the `.pm` glue files
//! (`PVE/RS/Meta.pm`, `Proxmox/Lib/PVEMeta.pm`) are generated separately by
//! `genpackage.pl` (see `Makefile`), not by this crate.
//!
//! The store root defaults to `/etc/pve/meta` and can be overridden with the
//! `PVE_META_ROOT` environment variable (used by tests and by
//! `test/basic.pl`).

use std::path::PathBuf;

use pve_meta_core::error::Error as CoreError;
use pve_meta_core::format::{self, Format};
use pve_meta_core::store::{MetaStore, RollbackOutcome, DISK_FORMAT};

/// Opens a fresh [`MetaStore`] rooted at `$PVE_META_ROOT`, or
/// `/etc/pve/meta` if unset. Cheap: `MetaStore::new` does no I/O.
fn open_store() -> MetaStore {
    let root = std::env::var_os("PVE_META_ROOT")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("/etc/pve/meta"));
    MetaStore::new(root)
}

/// Splits an `export_for_backup` blob into its `#pve-meta-format: <ext>`
/// header and the raw document text that follows it.
///
/// Documents are YAML on disk (`docs/DESIGN.md` §8), so the header this
/// crate *writes* always says `yaml`; it is still parsed on import so a blob
/// produced by an older build (which could say `json`) still restores — the
/// content is re-dumped as YAML on the way in.
fn split_backup_header(data: &str) -> anyhow::Result<(Format, &str)> {
    let (header, rest) = data
        .split_once('\n')
        .ok_or_else(|| anyhow::anyhow!("missing '#pve-meta-format: <ext>' header"))?;
    let ext = header
        .strip_prefix("#pve-meta-format: ")
        .ok_or_else(|| anyhow::anyhow!("malformed pve-meta backup header: {header:?}"))?;
    let format = Format::from_ext(ext)
        .ok_or_else(|| anyhow::anyhow!("unknown pve-meta backup format '{ext}'"))?;
    Ok((format, rest))
}

/// The `Proxmox::Lib::PVEMeta` library-loader package generated by
/// `genpackage.pl` (`--lib-package=Proxmox::Lib::PVEMeta`, see `Makefile`)
/// bootstraps itself on `use` (its own generated `BEGIN` block), so this crate
/// must export a matching `boot_Proxmox__Lib__PVEMeta` symbol even though it
/// has no functions of its own to export -- mirrors upstream `pve-rs`'s
/// `Proxmox::Lib::PVE` package (`proxmox-perl-rs/pve-rs/src/bindings/mod.rs`).
#[perlmod::package(name = "Proxmox::Lib::PVEMeta", lib = "pve_meta_rs")]
mod proxmox_lib_pve_meta {}

#[perlmod::package(name = "PVE::RS::Meta", lib = "pve_meta_rs")]
mod pve_rs_meta {
    //! The `PVE::RS::Meta` package: guest metadata lifecycle hooks, called
    //! from PVE's guest lifecycle code (snapshot/rollback/clone/destroy) and
    //! from vzdump backup/restore, plus the `api_*` functions used by
    //! `PVE::API2::Ext::Meta`.

    use anyhow::Error;

    use pve_meta_core::api;
    use pve_meta_core::store::DocId;

    use super::{format, open_store, split_backup_header, RollbackOutcome, DISK_FORMAT};

    /// Copies `$vmid`'s current document to its `$snapname` snapshot file.
    /// A no-op if the guest has no document.
    ///
    /// Returns `1` if a copy was made, `0` otherwise.
    #[export]
    pub fn on_snapshot(vmid: u32, snapname: &str) -> Result<bool, Error> {
        Ok(open_store().snapshot(vmid, snapname)?)
    }

    /// Restores `$vmid`'s `$snapname` snapshot copy over its current
    /// document. If no snapshot copy exists but a current document does, the
    /// current document is removed (the guest had no metadata when the
    /// snapshot was taken).
    ///
    /// Returns `"restored"`, `"removed"`, or `"none"`.
    #[export]
    pub fn on_rollback(vmid: u32, snapname: &str) -> Result<String, Error> {
        let outcome = open_store().rollback(vmid, snapname)?;
        Ok(match outcome {
            RollbackOutcome::Restored => "restored",
            RollbackOutcome::RemovedNoSnapshot => "removed",
            RollbackOutcome::NoOp => "none",
        }
        .to_string())
    }

    /// Removes `$vmid`'s `$snapname` snapshot copy. Idempotent.
    ///
    /// Returns `1` if a copy existed and was removed, `0` otherwise.
    #[export]
    pub fn on_delsnap(vmid: u32, snapname: &str) -> Result<bool, Error> {
        let store = open_store();
        let existed = store.list_snapshots(vmid)?.iter().any(|n| n == snapname);
        store.delete_snapshot(vmid, snapname)?;
        Ok(existed)
    }

    /// Copies `$vmid`'s current document (not its snapshots) to `$newid`,
    /// *overwriting* any document `$newid` already has -- mirroring
    /// `PVE::Firewall::Helpers::clone_vmfw_conf`'s unlink-then-copy, soft-fail
    /// clone (a stale target document left over from an earlier destroy race
    /// must not block a clone).
    ///
    /// A no-op if `$vmid` has no document; in that case any stale document
    /// `$newid` already has is still removed, so the (failed) clone leaves
    /// `$newid` clean.
    ///
    /// Returns `1` if a copy was made, `0` otherwise.
    #[export]
    pub fn on_clone(vmid: u32, newid: u32) -> Result<bool, Error> {
        let store = open_store();
        let src = match store.read(DocId::Guest(vmid)) {
            Ok(doc) => doc,
            Err(super::CoreError::NotFound(_)) => {
                if store.locate(DocId::Guest(newid))?.is_some() {
                    store.delete(DocId::Guest(newid))?;
                }
                return Ok(false);
            }
            Err(e) => return Err(e.into()),
        };
        // `put_raw` with no expected digest always creates-or-overwrites, so
        // this never dies on an existing `$newid` document.
        store.put_raw(DocId::Guest(newid), &src.raw, None)?;
        Ok(true)
    }

    /// Removes `$vmid`'s document and all of its snapshot copies. Idempotent.
    ///
    /// This is the *only* caller of the cascading
    /// [`pve_meta_core::store::MetaStore::destroy`]; the REST API's `DELETE`
    /// removes the current document only (`docs/DESIGN.md` §8).
    ///
    /// Returns the number of files removed.
    #[export]
    pub fn on_destroy(vmid: u32) -> Result<u32, Error> {
        let store = open_store();
        let snapshots = store.list_snapshots(vmid)?.len() as u32;
        let had_document = store.locate(DocId::Guest(vmid))?.is_some();
        store.destroy(vmid)?;
        Ok(snapshots + u32::from(had_document))
    }

    /// Returns `undef` if `$vmid` has no document, else a string
    /// `"#pve-meta-format: yaml\n"` followed by the document's raw text.
    /// The header records the format so `import_from_backup` can restore an
    /// older blob without re-guessing; it is stripped on import (and would
    /// otherwise just be a harmless comment line in YAML).
    #[export]
    pub fn export_for_backup(vmid: u32) -> Result<Option<String>, Error> {
        match open_store().read(DocId::Guest(vmid)) {
            Ok(doc) => Ok(Some(format!(
                "#pve-meta-format: {}\n{}",
                DISK_FORMAT.ext(),
                doc.raw
            ))),
            Err(super::CoreError::NotFound(_)) => Ok(None),
            Err(e) => Err(e.into()),
        }
    }

    /// Parses the `"#pve-meta-format: <ext>\n..."` blob produced by
    /// `export_for_backup` and writes it as `$vmid`'s document, replacing any
    /// existing document for that vmid. The content is validated through the
    /// core parser/lint before being written; dies on invalid content.
    ///
    /// **The store is YAML-only, the import is not** (`docs/DESIGN.md` §8,
    /// review F26/§6): a blob is a *backup*, and a backup taken by an older
    /// build may legitimately name another format in its header. Such a blob
    /// is parsed in the format it declares and re-dumped as YAML, so the
    /// asymmetry ends at the file: nothing but YAML is ever stored. Refusing
    /// it instead would make an old archive unrestorable for no gain.
    ///
    /// Failure is safe for the caller: the restore path in
    /// `PVE::API2::LXC`'s `create_vm` sets `$destroy_config_on_error = 1`
    /// unconditionally before the hook runs, so a die here leaves no
    /// half-restored guest behind.
    ///
    /// Always returns `1`.
    #[export]
    pub fn import_from_backup(vmid: u32, data: &str) -> Result<bool, Error> {
        let (blob_format, text) = split_backup_header(data)?;
        let store = open_store();
        if blob_format == DISK_FORMAT {
            // Byte-for-byte restore (put_raw still parses and lints it).
            store.put_raw(DocId::Guest(vmid), text, None)?;
        } else {
            // A blob from an older build may name another format; convert it
            // to the one on-disk format instead of refusing the restore.
            let value = format::parse(blob_format, text)?;
            store.put_raw(DocId::Guest(vmid), &format::dump(DISK_FORMAT, &value), None)?;
        }
        Ok(true)
    }

    /// Returns an array ref of `$vmid`'s snapshot names.
    #[export]
    pub fn list_snapshots(vmid: u32) -> Result<Vec<String>, Error> {
        Ok(open_store().list_snapshots(vmid)?)
    }

    /// Returns `1` if `$vmid` has a document, `0` otherwise.
    #[export]
    pub fn has_document(vmid: u32) -> Result<bool, Error> {
        Ok(open_store().locate(DocId::Guest(vmid))?.is_some())
    }

    /// Returns this crate's version string. Used by
    /// `crates/pve-meta-perl/test/basic.pl` and available to operators for
    /// checking which build a running pvedaemon/pveproxy has loaded.
    #[export]
    pub fn version() -> String {
        env!("CARGO_PKG_VERSION").to_string()
    }

    // -- API-shaped exports (`PVE::API2::Ext::Meta`, `docs/DESIGN.md` §3) --
    //
    // Thin wrappers over `pve_meta_core::api` (see that module's docs for the
    // wire contract and the authorization rules). All of these die with a
    // Rust `anyhow::Error` whose `Display` is `"NNN: message"` (an HTTP
    // status prefix); the Perl layer parses that prefix and re-raises via
    // `PVE::Exception::raise`.

    /// `GET /meta/version` -> `{ token, changed }`.
    #[export]
    pub fn api_version() -> Result<api::ApiVersion, Error> {
        api::version(&open_store())
    }

    /// The datacenter document's `scopes` entries for `$authid`, as a JSON
    /// array of `{prefix, mode}` (used by `GET /meta/access` and to build
    /// the `grants_json` passed to the other `api_*` functions).
    #[export]
    pub fn api_grants(authid: &str) -> Result<String, Error> {
        api::grants(&open_store(), authid)
    }

    /// `GET /meta/guests`. `$guests_json` is the JSON array of vmlist rows
    /// Perl already has -- `[{vmid, node, type, name, grants}]`, where
    /// `grants` is that guest's grants as a JSON string. Rust never reads
    /// `.vmlist` or a guest config itself.
    ///
    /// `$orphans` (the caller has `Sys.Audit` on `/`) additionally lists
    /// every document whose vmid is *not* among those rows, marked
    /// `orphan => 1` (`docs/DESIGN.md` §9): the guest is gone, so there is no
    /// `/vms/<vmid>` ACL to ask and the datacenter read is the permission.
    #[export]
    pub fn api_list_guests(
        guests_json: &str,
        has: Option<&str>,
        orphans: bool,
    ) -> Result<Vec<api::GuestListEntry>, Error> {
        api::list_guests(&open_store(), guests_json, has, orphans)
    }

    /// `GET /meta/guests/{vmid}` / `GET /meta/datacenter` (`$id` is a vmid
    /// or `"datacenter"`).
    #[export]
    pub fn api_get(
        id: &str,
        view: Option<&str>,
        format: &str,
        comments: bool,
        grants_json: &str,
    ) -> Result<api::ApiViewDocument, Error> {
        api::get_document(&open_store(), id, view, format, comments, grants_json)
    }

    /// `PUT /meta/guests/{vmid}` / `PUT /meta/datacenter`.
    ///
    /// The caller (`PVE::API2::Ext::Meta`) must already hold the document's
    /// `cfs_lock_domain` lock: the digest precondition is re-checked inside
    /// this call, but only a lock makes the read-modify-write atomic across
    /// nodes (`docs/DESIGN.md` §8).
    #[export]
    #[allow(clippy::too_many_arguments)] // matches the PUT endpoint's parameter set 1:1 (docs/DESIGN.md §3)
    pub fn api_put(
        id: &str,
        view: Option<&str>,
        format: &str,
        payload: &str,
        mode: &str,
        digest: Option<&str>,
        dry_run: bool,
        grants_json: &str,
    ) -> Result<api::ApiPutResult, Error> {
        api::put_document(
            &open_store(),
            id,
            view,
            format,
            payload,
            mode,
            digest,
            dry_run,
            grants_json,
        )
    }

    /// `DELETE /meta/guests/{vmid}` / `DELETE /meta/datacenter`. Removes the
    /// current document only -- never a snapshot copy.
    #[export]
    pub fn api_delete(
        id: &str,
        view: Option<&str>,
        digest: Option<&str>,
        grants_json: &str,
    ) -> Result<api::ApiPutResult, Error> {
        api::delete_document(&open_store(), id, view, digest, grants_json)
    }
}
